on:
    push:
      branches: 
        - main
    workflow_dispatch:

jobs:
    store-front:
        runs-on: ubuntu-24.04
        steps:
            - name: GDR - Checkout code
              uses: actions/checkout@v2

            - name: GDR - install dependencies
              run: npm install
              working-directory: src/store-front

            - name: GDR - build the package
              run: npm run build
              working-directory: src/store-front

            - name: GDR - Zip build output
              run: zip -r dist.zip src/store-front/dist/

            - name: GDR - Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: GDR - build-artifact
                path: dist.zip
